version: '3.8'

services:
  database:
    container_name: myther-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mytherdb
      MYSQL_USER: mytheruser
      MYSQL_PASSWORD: mytherpass
    ports:
      - '4306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./build/php
    expose:
      - "9000"
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/myther-app
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/myther-app
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

